# Generated by Django 5.1.1 on 2024-09-23 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('adress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('about', models.CharField(max_length=255)),
                ('delivery', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Diambil', 'Diambil'), ('Proses', 'Proses'), ('Batal', 'Batal'), ('Selesai', 'Selesai'), ('Pending', 'Pending')], max_length=10)),
                ('time', models.DateTimeField()),
                ('qty', models.IntegerField()),
                ('customer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.customers')),
                ('service_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.services')),
            ],
        ),
    ]
