# Generated by Django 5.1.1 on 2024-09-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='time',
        ),
    ]
