# Generated by Django 5.1.1 on 2024-10-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_remove_transactions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('Picked Up', 'Picked Up'), ('Process', 'Process'), ('Canceled', 'Canceled'), ('Done', 'Done'), ('Pending', 'Pending')], max_length=10),
        ),
    ]
