# Generated by Django 5.1.1 on 2024-10-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_alter_transactions_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='delivery',
        ),
        migrations.AddField(
            model_name='services',
            name='max_load',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
