# Generated by Django 5.1.1 on 2024-10-01 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0004_remove_services_delivery_services_max_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='delivery',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transaction_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transation_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.transactions')),
            ],
        ),
    ]
